---
# binds zsh config

- name: assert binding of oh-my-zsh
  command: test -d ~/.oh-my-zsh
  ignore_errors: True
  register: omz_bound

- name: backup .zshrc
  command: cp ~/.zshrc ~/.zshrc.orig
  ignore_errors: True
  when: omz_bound|failed

- name: symlink oh-my-zsh
  file: state=link src=~/src/github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  when: omz_bound|failed

- name: copy oh-my-zsh template
  copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc
  when: omz_bound|failed

- name: change shell
  command: chsh -s /bin/zsh
  when: omz_bound|failed
