---
# installs homebrew system-wide

- name: clone homebrew
  git: repo=https://github.com/Homebrew/homebrew.git dest={{ brew_repo_path }}

- name: link the repo to the brew installation path
  file: state=link src={{ brew_repo_path }} dest={{ brew_install_path }} owner={{ ansible_user_id }}
  when: brew_repo_path != brew_install_path
