---
# shim rbenv

- name: ensure bash_profile presence
  ignore_errors: True
  file: path=~/.bash_profile state=touch

- name: ensure zshenv presence
  ignore_errors: True
  file: path=~/.zshenv state=touch

- name: add shim to bash
  lineinfile: dest=~/.bash_profile regexp="rbenv" line="eval \"$(rbenv init -)\"" state=present

- name: add shim to zsh
  lineinfile: dest=~/.zshenv regexp="rbenv" line="eval \"$(rbenv init -)\"" state=present
